export default {
  app: { name: 'English Helper', loading: 'Đang tải…', retry: 'Thử lại', cancel: 'Hủy', save: 'Lưu', delete: 'Xóa', edit: 'Sửa', add: 'Thêm', back: 'Quay lại', done: 'Xong', error: 'Đã xảy ra lỗi', empty: 'Chưa có nội dung', confirm: 'Xác nhận' },
  tabs: { home: 'Trang chủ', vocabulary: 'Từ vựng', review: 'Ôn tập', search: 'Tìm kiếm', settings: 'Cài đặt' },
  home: { greeting: 'Xây dựng vốn từ vựng', total: 'Tổng số từ', reviewed: 'Đã ôn tập', new: 'Chưa ôn tập', recent: 'Thêm gần đây', quickReview: 'Ôn tập nhanh', noWords: 'Hãy thêm từ đầu tiên để bắt đầu.' },
  vocabulary: { title: 'Từ vựng', add: 'Thêm từ', word: 'Từ tiếng Anh', vietnameseMeaning: 'Nghĩa tiếng Việt', englishMeaning: 'Nghĩa tiếng Anh', imageUrl: 'URL hình ảnh (tùy chọn)', imagePreview: 'Xem trước hình ảnh', imageUnavailable: 'Không thể tải hình ảnh', dateAdded: 'Ngày thêm', reviewCount: 'Số lần ôn tập', correctCount: 'Đúng', incorrectCount: 'Sai', noWords: 'Chưa có từ vựng.', required: 'Nhập từ và cả hai nghĩa.', invalidImageUrl: 'Nhập URL HTTP hoặc HTTPS hợp lệ.', saveError: 'Không thể lưu từ này.', deleteTitle: 'Xóa từ?', deleteMessage: 'Thao tác này sẽ xóa vĩnh viễn từ vựng.', deleteError: 'Không thể xóa từ này.', notFound: 'Không tìm thấy từ.', duplicate: 'Từ và các nghĩa này đã tồn tại.', openOxford: 'Mở từ điển Oxford', openCambridge: 'Mở từ điển Cambridge' },
  search: { title: 'Tìm từ vựng', placeholder: 'Tìm từ hoặc nghĩa', noResults: 'Không có kết quả phù hợp.' },
  review: { title: 'Ôn tập', byGroup: 'Ôn tập theo nhóm', random: 'Từ ngẫu nhiên', mistaken: 'Từ sai nhiều nhất', newest: 'Từ mới nhất', selectGroup: 'Chọn nhóm', groupLabel: 'Nhóm {{group}} · Từ {{start}}–{{end}}', chooseCount: 'Ôn tập bao nhiêu từ?', customCount: 'Số tùy chọn', start: 'Bắt đầu ôn tập', noWords: 'Thêm từ vựng trước khi ôn tập.', invalidCount: 'Chọn số từ 1 đến {{max}}.', vietnamese: 'Tiếng Việt', english: 'Tiếng Anh', yourAnswer: 'Câu trả lời', previous: 'Trước', next: 'Tiếp', skip: 'Bỏ qua', progress: '{{current}} / {{total}}', submit: 'Nộp bài ôn tập', submitTitle: 'Nộp bài ôn tập?', submitMessage: 'Câu trả lời và thống kê sẽ được lưu.', submitError: 'Không thể nộp bài ôn tập.', results: 'Kết quả ôn tập', total: 'Tổng số câu', correct: 'Đúng', incorrect: 'Sai', skipped: 'Bỏ qua', score: 'Điểm', correctWord: 'Từ đúng', userAnswer: 'Câu trả lời của bạn', unanswered: 'Chưa trả lời', tryAgain: 'Ôn tập lần nữa', noSession: 'Không có lượt ôn tập nào.' },
  settings: { title: 'Cài đặt', language: 'Ngôn ngữ', english: 'Tiếng Anh', vietnamese: 'Tiếng Việt', groupSize: 'Số từ mỗi nhóm ôn tập', invalidGroupSize: 'Nhập số nguyên dương.', export: 'Xuất từ vựng', import: 'Nhập từ vựng', importSummary: 'Đã nhập: {{imported}}\nBỏ qua trùng lặp: {{duplicates}}\nKhông hợp lệ: {{invalid}}', exportSuccess: 'Bản sao lưu đã sẵn sàng để chia sẻ.', exportError: 'Không thể xuất từ vựng.', importError: 'Không thể nhập tệp này.', unsupportedBackup: 'Phiên bản sao lưu không được hỗ trợ.', malformedBackup: 'Đây không phải bản sao lưu từ vựng hợp lệ.', fileError: 'Không thể đọc tệp đã chọn.' },
  dictionary: { openError: 'Không thể mở trang từ điển.' },
} as const;
