export default {
  reviewNavigation: { label: 'Từ số {{number}}, {{state}}', openDetails: 'Mở chi tiết từ {{word}}', state: { current: 'đang chọn', answered: 'đã trả lời', pending: 'đã bỏ qua hoặc chưa trả lời', unvisited: 'chưa xem' } },
  app: { menu: 'Menu', name: 'English Helper', loading: 'Đang tải…', retry: 'Thử lại', cancel: 'Hủy', save: 'Lưu', delete: 'Xóa', edit: 'Sửa', add: 'Thêm', back: 'Quay lại', done: 'Xong', error: 'Đã xảy ra lỗi', empty: 'Chưa có nội dung', confirm: 'Xác nhận' },
  tabs: { home: 'Trang chủ', review: 'Ôn tập', settings: 'Cài đặt', profile: 'Hồ sơ' },
  home: { yourVocabulary: 'Từ vựng của bạn', greeting: 'Xây dựng vốn từ vựng', total: 'Tổng số từ', reviewed: 'Đã ôn tập', new: 'Chưa ôn tập', recent: 'Thêm gần đây', quickReview: 'Ôn tập nhanh', noWords: 'Hãy thêm từ đầu tiên để bắt đầu.' },
  vocabulary: { addNew: 'Thêm từ mới', editWord: 'Sửa từ', wordRequired: 'Từ mới *', wordClass: 'Loại từ', vietnameseMeaningRequired: 'Nghĩa tiếng Việt *', englishMeaningRequired: 'Nghĩa tiếng Anh *', selectWordClass: 'Chọn loại từ', ipa: 'Phiên âm quốc tế', title: 'Từ vựng', add: 'Thêm từ', word: 'Từ tiếng Anh', vietnameseMeaning: 'Nghĩa tiếng Việt', englishMeaning: 'Nghĩa tiếng Anh', imageUrl: 'URL hình ảnh (tùy chọn)', imagePreview: 'Xem trước hình ảnh', imageUnavailable: 'Không thể tải hình ảnh', dateAdded: 'Ngày thêm', reviewCount: 'Số lần ôn tập', correctCount: 'Đúng', incorrectCount: 'Sai', noWords: 'Chưa có từ vựng.', required: 'Nhập từ và cả hai nghĩa.', invalidImageUrl: 'Nhập URL HTTP hoặc HTTPS hợp lệ.', saveError: 'Không thể lưu từ này.', deleteTitle: 'Xóa từ?', deleteMessage: 'Thao tác này sẽ xóa vĩnh viễn từ vựng.', deleteError: 'Không thể xóa từ này.', notFound: 'Không tìm thấy từ.', duplicate: 'Từ và các nghĩa này đã tồn tại.', openOxford: 'Mở từ điển Oxford', openCambridge: 'Mở từ điển Cambridge' },
  search: { clear: 'Xóa tìm kiếm', title: 'Tìm từ vựng', placeholder: 'Tìm từ hoặc nghĩa', noResults: 'Không có kết quả phù hợp.' },
  review: { title: 'Ôn tập', byGroup: 'Ôn tập theo nhóm', random: 'Từ ngẫu nhiên', mistaken: 'Từ sai nhiều nhất', newest: 'Từ mới nhất', selectGroup: 'Chọn nhóm', groupLabel: 'Nhóm {{group}} · Từ {{start}}–{{end}}', chooseCount: 'Ôn tập bao nhiêu từ?', customCount: 'Số tùy chọn', start: 'Bắt đầu ôn tập', noWords: 'Thêm từ vựng trước khi ôn tập.', invalidCount: 'Chọn số từ 1 đến {{max}}.', vietnamese: 'Tiếng Việt', english: 'Tiếng Anh', yourAnswer: 'Câu trả lời', previous: 'Trước', next: 'Tiếp', skip: 'Bỏ qua', progress: '{{current}} / {{total}}', submit: 'Nộp bài ôn tập', submitTitle: 'Nộp bài ôn tập?', submitMessage: 'Câu trả lời và thống kê sẽ được lưu.', submitError: 'Không thể nộp bài ôn tập.', results: 'Kết quả ôn tập', total: 'Tổng số câu', correct: 'Đúng', incorrect: 'Sai', skipped: 'Bỏ qua', score: 'Điểm', correctWord: 'Từ đúng', userAnswer: 'Câu trả lời của bạn', unanswered: 'Chưa trả lời', tryAgain: 'Ôn tập lần nữa', noSession: 'Không có lượt ôn tập nào.' },
  settings: { title: 'Cài đặt', language: 'Ngôn ngữ', english: 'Tiếng Anh', vietnamese: 'Tiếng Việt', groupSize: 'Số từ mỗi nhóm ôn tập', invalidGroupSize: 'Nhập số nguyên dương.', export: 'Xuất từ vựng', import: 'Nhập từ vựng', importSummary: 'Đã nhập: {{imported}}\nBỏ qua trùng lặp: {{duplicates}}\nKhông hợp lệ: {{invalid}}', exportSuccess: 'Bản sao lưu đã sẵn sàng để chia sẻ.', exportError: 'Không thể xuất từ vựng.', importError: 'Không thể nhập tệp này.', unsupportedBackup: 'Phiên bản sao lưu không được hỗ trợ.', malformedBackup: 'Đây không phải bản sao lưu từ vựng hợp lệ.', fileError: 'Không thể đọc tệp đã chọn.' },
  auth: { email: 'Email', emailRequired: 'Email *', password: 'Mật khẩu', passwordRequired: 'Mật khẩu *', confirmPasswordRequired: 'Xác nhận mật khẩu *', login: 'Đăng nhập', signUp: 'Đăng ký', signIn: 'Đăng nhập', noAccount: 'Chưa có tài khoản?', haveAccount: 'Đã có tài khoản?', rememberMe: 'Ghi nhớ đăng nhập', forgotPassword: 'Quên mật khẩu?', localRecoveryUnavailable: 'Khôi phục mật khẩu cần dịch vụ email trong tương lai. Vui lòng dùng mật khẩu hiện tại hoặc tạo tài khoản mới.', showPassword: 'Hiện mật khẩu', hidePassword: 'Ẩn mật khẩu', required: 'Điền các trường bắt buộc.', invalidEmail: 'Nhập email hợp lệ.', weakPassword: 'Mật khẩu cần 8–128 ký tự.', passwordMismatch: 'Mật khẩu xác nhận không khớp.', duplicateEmail: 'Email này đã được đăng ký.', invalidCredentials: 'Email hoặc mật khẩu không đúng.', incorrectCurrentPassword: 'Mật khẩu hiện tại không đúng.', invalidDisplayName: 'Tên cần có 1–60 ký tự.', invalidAvatarUrl: 'Nhập URL ảnh HTTP hoặc HTTPS.', unavailable: 'Không thể hoàn thành thao tác tài khoản.' },
  profile: { title: 'Hồ sơ', edit: 'Sửa hồ sơ', changePassword: 'Đổi mật khẩu', logout: 'Đăng xuất', displayName: 'Tên hiển thị', avatarUrl: 'URL ảnh đại diện', currentPassword: 'Mật khẩu hiện tại *', newPassword: 'Mật khẩu mới *', confirmNewPassword: 'Xác nhận mật khẩu mới *', updateError: 'Không thể cập nhật hồ sơ.' },
  wordClasses: { noun: 'Danh từ', verb: 'Động từ', adjective: 'Tính từ', adverb: 'Trạng từ', pronoun: 'Đại từ', preposition: 'Giới từ', conjunction: 'Liên từ', interjection: 'Thán từ', determiner: 'Từ hạn định', article: 'Mạo từ', auxiliaryVerb: 'Trợ động từ', modalVerb: 'Động từ tình thái', phrasalVerb: 'Cụm động từ', idiom: 'Thành ngữ', phrase: 'Cụm từ', abbreviation: 'Viết tắt', acronym: 'Từ viết tắt', numeral: 'Số từ', prefix: 'Tiền tố', suffix: 'Hậu tố', other: 'Khác' },
  dictionary: { openError: 'Không thể mở trang từ điển.' },
} as const;
