export default {
  reviewNavigation: { label: 'Word {{number}}, {{state}}', openDetails: 'Open details for {{word}}', state: { current: 'current', answered: 'answered', pending: 'skipped or unanswered', unvisited: 'not visited' } },
  app: { name: 'English Helper', loading: 'Loading…', retry: 'Retry', cancel: 'Cancel', save: 'Save', delete: 'Delete', edit: 'Edit', add: 'Add', back: 'Back', menu: 'Menu', done: 'Done', error: 'Something went wrong', empty: 'Nothing here yet', confirm: 'Confirm' },
  tabs: { home: 'Home', review: 'Review', settings: 'Settings', profile: 'Profile' },
  home: { yourVocabulary: 'Your Vocabulary', greeting: 'Build your vocabulary', total: 'Total words', reviewed: 'Words reviewed', new: 'Not reviewed yet', recent: 'Recently added', quickReview: 'Quick start review', noWords: 'Add your first word to begin.' },
  vocabulary: { addNew: 'Add New Word', editWord: 'Edit Word', wordRequired: 'New Word *', wordClass: 'Word Class', vietnameseMeaningRequired: 'Vietnamese Meaning *', englishMeaningRequired: 'English Meaning *', selectWordClass: 'Select word class', ipa: 'International Phonetic Alphabet', title: 'Vocabulary', add: 'Add word', word: 'English word', vietnameseMeaning: 'Vietnamese meaning', englishMeaning: 'English meaning', imageUrl: 'Image URL (optional)', imagePreview: 'Image preview', imageUnavailable: 'Image unavailable', dateAdded: 'Date added', reviewCount: 'Times reviewed', correctCount: 'Correct', incorrectCount: 'Incorrect', noWords: 'No vocabulary yet.', required: 'Fill in the word and both meanings.', invalidImageUrl: 'Enter a valid HTTP or HTTPS URL.', saveError: 'Could not save this word.', deleteTitle: 'Delete word?', deleteMessage: 'This permanently removes the vocabulary record.', deleteError: 'Could not delete this word.', notFound: 'Word not found.', duplicate: 'This word and meanings already exist.', openOxford: 'Open Oxford Dictionary', openCambridge: 'Open Cambridge Dictionary' },
  search: { clear: 'Clear search', title: 'Search vocabulary', placeholder: 'Search words or meanings', noResults: 'No matching words.' },
  review: { title: 'Review', byGroup: 'Review by group', random: 'Random words', mistaken: 'Most mistaken words', newest: 'Newest words', selectGroup: 'Select a group', groupLabel: 'Group {{group}} · Words {{start}}–{{end}}', chooseCount: 'How many words?', customCount: 'Custom number', start: 'Start review', noWords: 'Add vocabulary before starting a review.', invalidCount: 'Choose a number from 1 to {{max}}.', vietnamese: 'Vietnamese', english: 'English', yourAnswer: 'Your answer', previous: 'Previous', next: 'Next', skip: 'Skip', progress: '{{current}} / {{total}}', submit: 'Submit review', submitTitle: 'Submit review?', submitMessage: 'Your answers and review statistics will be saved.', submitError: 'Could not submit the review.', results: 'Review results', total: 'Total questions', correct: 'Correct answers', incorrect: 'Incorrect answers', skipped: 'Skipped', score: 'Score', correctWord: 'Correct word', userAnswer: 'Your answer', unanswered: 'Unanswered', tryAgain: 'Start another review', noSession: 'No active review session.' },
  settings: { title: 'Settings', language: 'Language', english: 'English', vietnamese: 'Vietnamese', groupSize: 'Review group size', invalidGroupSize: 'Enter a positive whole number.', export: 'Export vocabulary', import: 'Import vocabulary', importSummary: 'Imported: {{imported}}\nDuplicates skipped: {{duplicates}}\nInvalid: {{invalid}}', exportSuccess: 'Backup ready to share.', exportError: 'Could not export vocabulary.', importError: 'Could not import this file.', unsupportedBackup: 'Unsupported backup version.', malformedBackup: 'This is not a valid vocabulary backup.', fileError: 'Could not read the selected file.' },
  auth: { email: 'Email', emailRequired: 'Email *', password: 'Password', passwordRequired: 'Password *', confirmPasswordRequired: 'Password Confirmation *', login: 'Login', signUp: 'Sign Up', signIn: 'Sign in', noAccount: 'Don’t have an account?', haveAccount: 'Already have an account?', rememberMe: 'Remember Me', forgotPassword: 'Forgot Password?', localRecoveryUnavailable: 'Password recovery requires a future email service. Please use your current password or create a new account.', showPassword: 'Show password', hidePassword: 'Hide password', required: 'Complete the required fields.', invalidEmail: 'Enter a valid email address.', weakPassword: 'Use 8–128 characters for your password.', passwordMismatch: 'Passwords do not match.', duplicateEmail: 'This email is already registered.', invalidCredentials: 'Incorrect email or password.', incorrectCurrentPassword: 'Current password is incorrect.', invalidDisplayName: 'Enter a name of 1–60 characters.', invalidAvatarUrl: 'Enter an HTTP or HTTPS image URL.', unavailable: 'Unable to complete this account action.' },
  profile: { title: 'Profile', edit: 'Edit Profile', changePassword: 'Change Password', logout: 'Logout', displayName: 'Display Name', avatarUrl: 'Avatar image URL', currentPassword: 'Current Password *', newPassword: 'New Password *', confirmNewPassword: 'Confirm New Password *', updateError: 'Unable to update profile.' },
  wordClasses: { noun: 'Noun', verb: 'Verb', adjective: 'Adjective', adverb: 'Adverb', pronoun: 'Pronoun', preposition: 'Preposition', conjunction: 'Conjunction', interjection: 'Interjection', determiner: 'Determiner', article: 'Article', auxiliaryVerb: 'Auxiliary Verb', modalVerb: 'Modal Verb', phrasalVerb: 'Phrasal Verb', idiom: 'Idiom', phrase: 'Phrase', abbreviation: 'Abbreviation', acronym: 'Acronym', numeral: 'Numeral / Number', prefix: 'Prefix', suffix: 'Suffix', other: 'Other' },
  dictionary: { openError: 'Could not open the dictionary page.' },
} as const;
