export default {
  app: { name: 'English Helper', loading: 'Loading…', retry: 'Retry', cancel: 'Cancel', save: 'Save', delete: 'Delete', edit: 'Edit', add: 'Add', back: 'Back', done: 'Done', error: 'Something went wrong', empty: 'Nothing here yet', confirm: 'Confirm' },
  tabs: { home: 'Home', vocabulary: 'Vocabulary', review: 'Review', search: 'Search', settings: 'Settings' },
  home: { greeting: 'Build your vocabulary', total: 'Total words', reviewed: 'Words reviewed', new: 'Not reviewed yet', recent: 'Recently added', quickReview: 'Quick start review', noWords: 'Add your first word to begin.' },
  vocabulary: { title: 'Vocabulary', add: 'Add word', word: 'English word', vietnameseMeaning: 'Vietnamese meaning', englishMeaning: 'English meaning', imageUrl: 'Image URL (optional)', imagePreview: 'Image preview', imageUnavailable: 'Image unavailable', dateAdded: 'Date added', reviewCount: 'Times reviewed', correctCount: 'Correct', incorrectCount: 'Incorrect', noWords: 'No vocabulary yet.', required: 'Fill in the word and both meanings.', invalidImageUrl: 'Enter a valid HTTP or HTTPS URL.', saveError: 'Could not save this word.', deleteTitle: 'Delete word?', deleteMessage: 'This permanently removes the vocabulary record.', deleteError: 'Could not delete this word.', notFound: 'Word not found.', duplicate: 'This word and meanings already exist.', openOxford: 'Open Oxford Dictionary', openCambridge: 'Open Cambridge Dictionary' },
  search: { title: 'Search vocabulary', placeholder: 'Search words or meanings', noResults: 'No matching words.' },
  review: { title: 'Review', byGroup: 'Review by group', random: 'Random words', mistaken: 'Most mistaken words', newest: 'Newest words', selectGroup: 'Select a group', groupLabel: 'Group {{group}} · Words {{start}}–{{end}}', chooseCount: 'How many words?', customCount: 'Custom number', start: 'Start review', noWords: 'Add vocabulary before starting a review.', invalidCount: 'Choose a number from 1 to {{max}}.', vietnamese: 'Vietnamese', english: 'English', yourAnswer: 'Your answer', previous: 'Previous', next: 'Next', skip: 'Skip', progress: '{{current}} / {{total}}', submit: 'Submit review', submitTitle: 'Submit review?', submitMessage: 'Your answers and review statistics will be saved.', submitError: 'Could not submit the review.', results: 'Review results', total: 'Total questions', correct: 'Correct answers', incorrect: 'Incorrect answers', skipped: 'Skipped', score: 'Score', correctWord: 'Correct word', userAnswer: 'Your answer', unanswered: 'Unanswered', tryAgain: 'Start another review', noSession: 'No active review session.' },
  settings: { title: 'Settings', language: 'Language', english: 'English', vietnamese: 'Vietnamese', groupSize: 'Review group size', invalidGroupSize: 'Enter a positive whole number.', export: 'Export vocabulary', import: 'Import vocabulary', importSummary: 'Imported: {{imported}}\nDuplicates skipped: {{duplicates}}\nInvalid: {{invalid}}', exportSuccess: 'Backup ready to share.', exportError: 'Could not export vocabulary.', importError: 'Could not import this file.', unsupportedBackup: 'Unsupported backup version.', malformedBackup: 'This is not a valid vocabulary backup.', fileError: 'Could not read the selected file.' },
  dictionary: { openError: 'Could not open the dictionary page.' },
} as const;
